/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#d0bcff",
        "on-secondary-fixed-variant": "#5516be",
        "on-surface": "#d4e4fa",
        "on-secondary": "#3c0091",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "primary-container": "#4d8eff",
        "on-tertiary-fixed": "#002113",
        "inverse-on-surface": "#233143",
        "on-primary": "#002e6a",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#6ffbbe",
        "error": "#ffb4ab",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#00a572",
        "secondary-container": "#571bc1",
        "background": "#051424",
        "on-primary-fixed-variant": "#004395",
        "surface-container-highest": "#273647",
        "on-primary-container": "#00285d",
        "surface-variant": "#273647",
        "secondary-fixed": "#e9ddff",
        "surface": "#051424",
        "on-primary-fixed": "#001a42",
        "on-secondary-container": "#c4abff",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#d4e4fa",
        "tertiary": "#4edea3",
        "surface-bright": "#2c3a4c",
        "primary": "#adc6ff",
        "surface-container-low": "#0d1c2d",
        "surface-dim": "#051424",
        "on-tertiary-fixed-variant": "#005236",
        "outline-variant": "#424754",
        "surface-container": "#122131",
        "surface-container-lowest": "#010f1f",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#00311f",
        "primary-fixed-dim": "#adc6ff",
        "on-background": "#d4e4fa",
        "outline": "#8c909f",
        "on-tertiary": "#003824",
        "surface-tint": "#adc6ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "64px",
        "xs": "4px",
        "md": "24px",
        "gutter": "24px",
        "base": "8px",
        "lg": "40px",
        "sm": "12px",
        "margin": "32px"
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "technical-sm": ["Roboto Mono", "monospace"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "technical-md": ["Roboto Mono", "monospace"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
